# Športno plezanje

Tu bom naredil projekt pri predmetu Programiranje 1.

## Priprava

Na začetku naložimo paket pandas za delo s podatki. V preambuli je še nekaj vrstic za lepše in lažje delo. Če CSV datoteke še ne obstajajo, jih najprej ustvarimo s pomočjo skripte pripravi_podatke.py.

In [23]:
import pandas as pd

pd.options.display.max_rows = 30
pd.options.display.max_columns = 16

rezultati = pd.read_csv('C:/Users/Uporabnik/Desktop/projekt/podatki.csv')

In [24]:
rezultati

,leto,kategorija,stevilo tekmovalcev,1. mesto,2. mesto,zadnje mesto,povprecje
0,2016,cicibanke,22,328,311,12,149.55
1,2016,cicibani,19,380,333,31,156.68
2,2016,mlajse deklice,31,330,325,4,115.71
3,2016,mlajsi decki,18,360,360,58,172.67
4,2016,starejse deklice,20,400,313,28,160.50
5,2016,starejsi decki,21,335,307,44,159.81
6,2016,kadetinje,12,400,310,37,191.67
7,2016,kadeti,11,345,315,150,216.18
8,2016,mladinke,8,260,231,65,161.75
9,2016,mladinci,9,280,247,43,153.89
10,2016,clanice,20,300,240,31,111.65
11,2016,clani,26,300,240,15,99.96
12,2015,cicibanke,23,390,294,37,144.22
13,2015,cicibani,15,380,325,24,185.87
14,2015,mlajse deklice,35,333,320,1,105.28
...,...,...,...,...,...,...,...
153,2004,mladinci,11,280,260,37,171.73
154,2004,clanice,13,300,225,31,141.69
155,2004,clani,31,280,280,7,89.68
156,2003,cicibanke,37,395,370,1,153.32
157,2003,cicibani,43,460,415,7,161.26
158,2003,mlajse deklice,20,500,405,20,211.85
159,2003,mlajsi decki,35,500,395,10,154.17
160,2003,starejse deklice,16,480,376,46,241.75
161,2003,starejsi decki,25,420,410,12,178.76
162,2003,kadetinje,9,500,460,80,267.67
163,2003,kadeti,19,465,425,22,215.95
164,2003,mladinke,7,245,240,98,176.43
165,2003,mladinci,6,300,260,51,207.67
166,2003,clanice,15,300,210,47,138.40
167,2003,clani,37,280,265,5,81.76

In [30]:
rezultati[rezultati["kategorija"] == "clani"]

,leto,kategorija,stevilo tekmovalcev,1. mesto,2. mesto,zadnje mesto,povprecje
11,2016,clani,26,300,240,15,99.96
23,2015,clani,36,293,260,2,77.44
35,2014,clani,39,280,220,5,75.18
47,2013,clani,38,300,245,1,79.05
59,2012,clani,37,265,225,1,77.30
71,2011,clani,34,296,277,10,108.56
83,2010,clani,33,231,230,18,86.45
95,2009,clani,38,300,225,5,77.24
107,2008,clani,41,300,225,5,70.24
119,2007,clani,28,280,280,14,93.39
131,2006,clani,29,300,231,9,89.83
143,2005,clani,29,240,200,10,84.07
155,2004,clani,31,280,280,7,89.68
167,2003,clani,37,280,265,5,81.76